# config.yaml
# (C) Copyright 2024- ECMWF.
#
# This software is licensed under the terms of the Apache Licence Version 2.0
# which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation
# nor does it submit to any jurisdiction.
#
# Configuration file for ecland_create_forcing.py script.
# Example for 1D ('sites') extraction.
#
# General information of the type of data to retrieve
sites:
    ftype: 1D                                 # 1D or 2D -- note that 2D allows only 1 "sitenames" (region) at the time 
                                              #             (and so iniDate, endDate, dx, clat*,clon* ...)
    group: LCS2026                               # Group the sites extracted under a common label/project, e.g. TERRENO,PLUMBER2 etc.
    sitenames:                                # site name code, MUST comply to XX-YYY for 1D, more flexible for 2D
        - CS-002
        - CS-003
        - CS-004
        - CS-005
        - CS-006
        - CS-007
        - CS-008
    iniDate:                                  # iniDate, one entry for each entry of sitename
        - 20170101
        - 20170101
        - 20211231
        - 20211231
        - 20211231
        - 20211231
        - 20211231
    endDate:                                  # endDate, one entry for each entry of sitename
        - 20211231
        - 20211231
        - 20211231
        - 20211231
        - 20211231
        - 20211231
        - 20211231

# This is only relevant for ftype=1D
point: 
    lat_lon:                                  # lat/lon pairs, one entry for each entry of sitename, 
        - 46.463,9.185                        # San Bernardino
        - 46.604,9.963                        # Zuoz
        - 46.558,7.890                        # Murren
        - 46.663,8.592                        # Andermatt
        - 46.505,8.308                        # Ulrichen
        - 46.813,9.848                        # Davos
        - 46.861,9.896                        # Kloster

    which_surface: 
        - land                                # Values accepted: orig (keep lsm/lake fraction from initial conditions, e.g. era5),
                                              #                  land (set 100% land fraction in input) 
                                              #                  lake (set 100% lake fraction in input)
                                              #                  grass (set 100% grass in input )
    actions: # Note order of the following items is important!
        - extract_initial_conditions: true   # Extract initial condition from database (mars or cds)
        - create_initial_conditions: true    # Create initial condition site netcdf
        - extract_create_forcing: true       # Extract and create forcing for site netcdf

# Configuration of folders, paths etc.
config:
    workingdir: /scratch/paga/oper_data_point_2             # working dir forcing
    inidir:     /scratch/paga/oper_data_point_2             # working dir initial cond
    sodir:      /perm/paga/ecland_input/clim/          # output dir for initial cond and static fields
    fodir:      /perm/paga/ecland_input/forcing/       # output dir for forcing
    scriptsdir: /home/paga/projects/ecland_opensource/ecland_LCS2026/tools/create_forcing/scripts/                   # Directory with create_forcing scripts
    retrieve_with: mars                                   # mars (ecmwf) or cds (climate data store)


# Initial condition and climate (static) fields
initial_conditions:
    INICLASS: "od"         # the class of the initial condition data  - only "ea" is supported for retrieve_with cds
    INISTREAM: oper        # the stream of the initial condition data - only oper is supported for retrieve_with cds
    INIEXPVER: 1           # the experiment version of the initial condition data - only 1 is supported for retrieve_with cds
    INIHOUR: "00:00:00"    # the time of the initial condition data - only "00:00:00" is supported for retrieve_with cds
    RESOL: "1279"           # the resolution used for the initial condition data and climate data, on the original gaussian grid used by ERA5 (639)
                           # only "639" is supported for retrieve_with cds
    GTYPE: "_4"           # the type of gaussian grid used by ERA5, "l_2" for linear reduced gaussian grid, 
                           # "_4" for cubic reduced gaussian grid. Only "l_2" is supported for retrieve_with cds
    CLIMVERSION: "v021"    # the version of the "climate" data used for the initial condition data. 
                                # ERA5 uses the v015
    clim_data_loc: "ecmwf" # the location of the climate data used for the initial condition data. 
                           # external users: "cds"
                           # emcwf (internal) users: "ecmwf" 

# Forcing
forcing:
    FORCINGCLASS: "od"                                    # the class of the forcing data, not yet used
    FORCINGSTREAM: oper                                   # the stream of the forcing data, not yet used
    FORCINGEXPVER: 1                                      # the experiment version of the forcing data, not yet used
    FORCINGHOUR: "00:00:00"                               # the time of the forcing data, not yet used
    forcingdir:  "/ec/fwsm/lb/project/surface_forcing/oper_monthly/" # Directory with pre-processed forcing (empty if no forcing is available).  
                                                          # This is also the directory where forcing will be saved if SAVE_FORCING_GRIB is true
    forcingCommonName: "forcing_od_1_oper_1"                                 # Name of the forcing file, filename convention accepted by the forcing extraction scripts: <forcingCommonName>_<YYYYMM00>.tar.gz
    SAVE_FORCING_GRIB: false                              # Save forcing downloaded from cds/mars in grib format to <forcingdir> for future use
    nthreads: 16                                           # Number of threads (parallel tasks) used for the forcing calculation. 
    
